#pragma once

// Logging for LumaCore. Backed by spdlog, active only in Debug builds.
//
// CMake defines LUMACORE_LOGGING_ENABLED for Debug but not for Release.
// In Release builds every LOG_* macro expands to nothing, so the logging code
// is fully stripped out and adds zero overhead to the shipped DLL.
// In Debug builds, logs are written to <Steam>\lumacore\main.log (and per-module
// files for each hook module registered in ModuleLog.h).
//
// Main logger macros (all modules):
//   LOG_INFO("loaded {} bytes", n);
//   LOG_WARN("pattern missed for {}", name);
//   LOG_ERROR("CopyFileA failed: err={}", GetLastError());
//   LOG_DEBUG("hook attempt {}/{}", i, max);
//
// Per-module loggers are generated from ModuleLog.h using the LC_MOD X-macro.
// Each module gets its own log file and its own set of LOG_<MODULE>_* macros,
// e.g. LOG_IPC_INFO, LOG_MANIFEST_WARN, LOG_DECRYPTIONKEY_ERROR.

#ifdef LUMACORE_LOGGING_ENABLED

#ifndef SPDLOG_ACTIVE_LEVEL
    #define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#endif

#include <spdlog/spdlog.h>
#include <spdlog/fmt/bin_to_hex.h>
#include <spdlog/sinks/basic_file_sink.h>
#include <windows.h>
#include <memory>

namespace Logger {
    void Init(HMODULE selfModule);
    void InitModules();

    inline std::shared_ptr<spdlog::logger> Main;

    // Per-module loggers declared via LC_MOD entries in ModuleLog.h
    #define LC_MOD(v, f) inline std::shared_ptr<spdlog::logger> v;
    #include "ModuleLog.h"
    #undef LC_MOD
}

// ── General-purpose (main.log) ──────────────────────────────────────
#define LOG_TRACE(...) SPDLOG_LOGGER_TRACE(Logger::Main, __VA_ARGS__)
#define LOG_DEBUG(...) SPDLOG_LOGGER_DEBUG(Logger::Main, __VA_ARGS__)
#define LOG_INFO(...)  SPDLOG_LOGGER_INFO(Logger::Main, __VA_ARGS__)
#define LOG_WARN(...)  SPDLOG_LOGGER_WARN(Logger::Main, __VA_ARGS__)
#define LOG_ERROR(...) SPDLOG_LOGGER_ERROR(Logger::Main, __VA_ARGS__)

#else  // LUMACORE_LOGGING_ENABLED

#include <windows.h>

namespace Logger {
    inline void Init(HMODULE) {}
    inline void InitModules() {}
}

#define LOG_TRACE(...)  ((void)0)
#define LOG_DEBUG(...)  ((void)0)
#define LOG_INFO(...)   ((void)0)
#define LOG_WARN(...)   ((void)0)
#define LOG_ERROR(...)  ((void)0)

#endif  // LUMACORE_LOGGING_ENABLED

// Per-module LOG_<MOD>_* macros generated by cmake/LogMacros.cmake.
#include "lc_log_macros.h"
